# Generated by Django 5.0.4 on 2024-04-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecords',
            name='amount_refunded',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='paymentrecords',
            name='refunded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
