# Generated by Django 5.0.4 on 2024-04-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0002_alter_paymentrecords_amount_refunded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecords',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymentrecords',
            name='refunded_at',
            field=models.DateTimeField(null=True),
        ),
    ]
